### ISSUE TITLE
Questions for weather people

### ISSUE THREAD

**Issue by geanders** [ropensci/rnoaa#151]
Please add in here any questions you have about weather data sources or how to use and interpret the data we're getting through these functions. This includes questions about how / why what is available through NOAA's APIs are different from other weather data sources.

**Comment by masalmon** [comment]
I have a question regarding NOAA sources, maybe someone will have a clue... I think the only station that I can access through rnoaa daily summaries function for Hyderabad is the one on this map http://www.imd.gov.in/pages/obs_network.php?id=08 (same lat and lon than the one I get with meteo_nearby_station) so the data must come from http://imdagrimet.gov.in/imd_datalist/form but if I use the form I get more data than what I get with rnoaa/NOAA: I get only RH and T with rnoaa but apparently with the form on imd.gov.in one gets daily summaries for all agro stations with more data than only RH and T. Am I missing something?

Is there a page somewhere with NOAA sources (@sckott maybe knows more)? I had to guess because I could not find the info. That said I'm quite sure I found what station it was, I'm just puzzled by the fact that NOAA may not pull all the available data.

**Comment by brian-may** [comment]
masalmon,

I think the station is question is this one: https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:PKM00041764/detail. As you can see NOAA only has TMAX, TMIN, and PRCP for this station. It may observer far more than this, but because it is not in the US the data is probably restricted.

You can read more about about the dataset provided by NOAA here: https://www.ncdc.noaa.gov/oa/climate/ghcn-daily/.

**Comment by masalmon** [comment]
@brian-may Thanks a lot, in particular it's helpful for me to know that you think that the data is probably restricted and from the second link I could surf a bit and find out more.

I forgot to mention I mean Hyderabad in India, this one is the Hyderabad in Pakistan (I always forget there are two Hyderabads!) This is the station http://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/stations/GHCND:IN001080500/detail

Here http://www1.ncdc.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt I see that the station is part of the GSN network. That's a pity not all the data that the station produces is made available through GSN but at least now I know it isn't!

**Comment by sckott** [comment]
@geanders can this be closed?
