### ISSUE TITLE
arc2 data

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#201]

**Comment by antoniospars** [comment]
Hi Scott devtools::install_github("ropensci/rnoaa") wont install in R 3.2

**Comment by antoniospars** [comment]
Downloading GitHub repo ropensci/rnoaa@master
from URL https://api.github.com/repos/ropensci/rnoaa/zipball/master
Installing rnoaa
Error in data.frame(package = package, installed = installed, available = available,  : 
  row names contain missing values

**Comment by sckott** [comment]
@antoniospars it wouldn't hurt to upgrade your R version - that's a separate issue 

for installing `rnoaa` - what operating system are you on?

**Comment by antoniospars** [comment]
Am using R 3.2.5 running on Windows 10.

On 22 Feb 2017 20:46, "Scott Chamberlain" <notifications@github.com> wrote:

@antoniospars <https://github.com/antoniospars> it wouldn't hurt to upgrade
your R version - that's a separate issue

for installing rnoaa - what operating system are you on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ropensci/rnoaa/issues/201#issuecomment-281745757>, or mute
the thread

**Comment by sckott** [comment]
trying to get a windows binary for you ..

**Comment by sckott** [comment]
[rnoaa_0.6.7.9199.zip](https://github.com/ropensci/rnoaa/files/794861/rnoaa_0.6.7.9199.zip)

@antoniospars  can you download and install this windows binary

e.g. like `install.packages("filepath", repos = NULL)`

**Comment by antoniospars** [comment]
Thanks

**Comment by sckott** [comment]
sorted
