### ISSUE TITLE
two gefs issues: broken test and leaving files in users /tmp directory

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#327]
@potterzot got an email from cran maintainers. We need to get a new version up with fixes in < 2 weeks, let me know if you don't have time and I'll hack something together

I imagine they saw this https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/rnoaa-00check.html which needs to be fixed

and then noticed that files were being left in the users tmp directory. list files in your global tmp directory, e.g, `list.files("/private/tmp/")`, then run `gefs_dimension_values(dim = "ens1")`, then you should see a new file in tmp like `occookieQjhsO6 ` after running that fxn 

For the failing test - it's failing on 2 different checks https://cranchecks.info/pkgs/rnoaa for the newest version of the pkg 

For the files left in tmp, i imagine those are coming from the call to `ncdf4::nc_open` inside of the call to `gefs_CONNECT`, but not sure of that.

**Comment by potterzot** [comment]
Thanks @sckott. I should be able to get to it quickly. I won't have a chance until tomorrow afternoon but I'll take a look then. 

I suspect this is a question of when the tests are run, since there's a lag and I think the test tries to access the previous day's file based on system date. But I can change this to two days previous to make sure it can find the file regardless of what time of the day the tests are run. That should be fast. The temp file issue seems quickly fixable as well so hopefully I can make a PR tomorrow afternoon.

**Comment by potterzot** [comment]
PS - would you mind assigning this issue to me? I don't have the rights to do that.

**Comment by sckott** [comment]
thanks, assigned you
