### ISSUE TITLE
ISD ftp access fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/rnoaa#76]
Work on making fxns to access ISD data from FTP because the legacy NCDC REST service is quite unreliable. It does provide search which is good, but FTP should be more reliable at least for getting data.

**Comment by swayland** [comment]
I've done some work on this since I use ISD data regularly. It might be worth considering starting with the ISD Lite data. It's way easier to work with as there are only 12 fields to parse. The granularity is not quite as good, and the times are rounded to the nearest hour, but the data is still good enough for most purposes. If it's something that you think is worthwhile. I'd be glad to give it a go.

**Comment by sckott** [comment]
thanks @swayland - Been a while since I worked on this. I'll look through the code as is and see where we're at

**Comment by sckott** [comment]
@swayland made some changes. Try reinstalling rnoaa from github, then trying its examples https://github.com/ropensci/rnoaa/blob/master/R/isd.R 

Let me know if you think the interface for the function is good, and behavior is good, and output data (column names, etc.) Note that we cache the original compressed (.gz) file, and then also the created .csv file (so that on subsequent calls to get the same data, we only have to read in the .csv - impt. b/c processing the ISD data takes a long time given the nasty messy strings of data)

**Comment by sckott** [comment]
seems done to me
